# https://github.com/devcontainers/templates/tree/main/src/typescript-node
# https://mcr.microsoft.com/en-us/product/devcontainers/typescript-node/about

# latest node
FROM mcr.microsoft.com/devcontainers/typescript-node

# needed for cypress headless esp. xvfb
RUN apt-get update && apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb




